name: Build Stampede with Pygbag
on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build-pygbag:
    name: Stampede Game Deployment
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Build with Pygbag
      run: |
        echo "Installing pygbag"
        python -m pip install pygbag
        echo "Building the game"
        python -m pygbag --build $GITHUB_WORKSPACE/main.py
        echo "Build complete"

    - name: "Deploy to gh-pages"
      uses: JamesIves/github-pages-deploy-action@4.1.7
      with:
        branch: gh-pages
        folder: build/web